/**
 * MSM AXIOM-7 Cloudflare Worker Proxy
  * Route: POST /api/axiom
   * Forwards requests to Groq API, hiding the API key server-side.
    * CORS locked to: https://devontallman.github.io
     * Rate limit: 20 requests per student UID per hour (Cloudflare KV)
      *
       * Environment variables (set via wrangler secret / CF dashboard):
        *   GROQ_API_KEY  — your Groq API key (never exposed to the browser)
         *
          * KV namespace binding (set in wrangler.toml):
           *   MSM_RATE_KV  — Cloudflare KV namespace for rate-limit counters
            */

            const ALLOWED_ORIGIN = 'https://devontallman.github.io';
            const GROQ_ENDPOINT  = 'https://api.groq.com/openai/v1/chat/completions';
            const RATE_LIMIT     = 20;          // max requests per UID per hour
            const RATE_WINDOW_S  = 3600;        // 1 hour in seconds

            // ── CORS headers ─────────────────────────────────────────────────────────────
            function corsHeaders(origin) {
              const allowed = origin === ALLOWED_ORIGIN ? origin : '';
                return {
                    'Access-Control-Allow-Origin':  allowed,
                        'Access-Control-Allow-Methods': 'POST, OPTIONS',
                            'Access-Control-Allow-Headers': 'Content-Type',
                                'Access-Control-Max-Age':       '86400',
                                  };
                                  }

                                  // ── JSON response helper ──────────────────────────────────────────────────────
                                  function jsonResponse(body, status, origin) {
                                    return new Response(JSON.stringify(body), {
                                        status,
                                            headers: {
                                                  'Content-Type': 'application/json',
                                                        ...corsHeaders(origin),
                                                            },
                                                              });
                                                              }

                                                              // ── Rate limiter (Cloudflare KV) ──────────────────────────────────────────────
                                                              async function checkRateLimit(env, uid, origin) {
                                                                if (!env.MSM_RATE_KV) {
                                                                    // KV not bound — allow (fail open for local dev / initial deploy)
                                                                        return { allowed: true, remaining: RATE_LIMIT };
                                                                          }

                                                                            const key     = `rl:${uid}`;
                                                                              const nowS    = Math.floor(Date.now() / 1000);
                                                                                const raw     = await env.MSM_RATE_KV.get(key);
                                                                                  let   counter = raw ? JSON.parse(raw) : { count: 0, windowStart: nowS };

                                                                                    // Reset window if expired
                                                                                      if (nowS - counter.windowStart >= RATE_WINDOW_S) {
                                                                                          counter = { count: 0, windowStart: nowS };
                                                                                            }

                                                                                              if (counter.count >= RATE_LIMIT) {
                                                                                                  const resetIn = RATE_WINDOW_S - (nowS - counter.windowStart);
                                                                                                      return { allowed: false, remaining: 0, resetIn };
                                                                                                        }
                                                                                                        
                                                                                                          counter.count += 1;
                                                                                                            const ttl = RATE_WINDOW_S - (nowS - counter.windowStart);
                                                                                                              await env.MSM_RATE_KV.put(key, JSON.stringify(counter), { expirationTtl: ttl });
                                                                                                              
                                                                                                                return { allowed: true, remaining: RATE_LIMIT - counter.count };
                                                                                                                }
                                                                                                                
                                                                                                                // ── Main handler ──────────────────────────────────────────────────────────────
                                                                                                                export default {
                                                                                                                  async fetch(request, env, ctx) {
                                                                                                                      const origin = request.headers.get('Origin') || '';
                                                                                                                      
                                                                                                                          // Reject non-allowed origins immediately
                                                                                                                              if (origin !== ALLOWED_ORIGIN) {
                                                                                                                                    return new Response('Forbidden', { status: 403 });
                                                                                                                                        }
                                                                                                                                        
                                                                                                                                            // Handle CORS pre-flight
                                                                                                                                                if (request.method === 'OPTIONS') {
                                                                                                                                                      return new Response(null, { status: 204, headers: corsHeaders(origin) });
                                                                                                                                                          }
                                                                                                                                                          
                                                                                                                                                              // Only POST to /api/axiom
                                                                                                                                                                  const url = new URL(request.url);
                                                                                                                                                                      if (request.method !== 'POST' || url.pathname !== '/api/axiom') {
                                                                                                                                                                            return jsonResponse({ error: 'Not found' }, 404, origin);
                                                                                                                                                                                }
                                                                                                                                                                                
                                                                                                                                                                                    // Parse body
                                                                                                                                                                                        let body;
                                                                                                                                                                                            try {
                                                                                                                                                                                                  body = await request.json();
                                                                                                                                                                                                      } catch {
                                                                                                                                                                                                            return jsonResponse({ error: 'Invalid JSON body' }, 400, origin);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                
                                                                                                                                                                                                                    const { prompt, studentAnswer, question, marks, topic, uid } = body;
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        // Validate required fields
                                                                                                                                                                                                                            if (!studentAnswer || !question) {
                                                                                                                                                                                                                                  return jsonResponse({ error: 'Missing required fields: question, studentAnswer' }, 400, origin);
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          // Rate limiting
                                                                                                                                                                                                                                              const studentUid = uid || request.headers.get('CF-Connecting-IP') || 'anon';
                                                                                                                                                                                                                                                  const rl = await checkRateLimit(env, studentUid, origin);
                                                                                                                                                                                                                                                      if (!rl.allowed) {
                                                                                                                                                                                                                                                            return jsonResponse(
                                                                                                                                                                                                                                                                    { error: `Rate limit reached. Try again in ${Math.ceil(rl.resetIn / 60)} minutes.` },
                                                                                                                                                                                                                                                                            429,
                                                                                                                                                                                                                                                                                    origin
                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                  // Check API key is configured
                                                                                                                                                                                                                                                                                                      if (!env.GROQ_API_KEY) {
                                                                                                                                                                                                                                                                                                            return jsonResponse({ error: 'Worker misconfiguration: GROQ_API_KEY not set.' }, 500, origin);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    // Build Groq request body — reconstructed server-side
                                                                                                                                                                                                                                                                                                                        // The full few-shot prompt is embedded here; the browser sends
                                                                                                                                                                                                                                                                                                                            // only question + answer metadata, never the API key.
                                                                                                                                                                                                                                                                                                                                const groqBody = {
                                                                                                                                                                                                                                                                                                                                      model:       'llama-3.3-70b-versatile',
                                                                                                                                                                                                                                                                                                                                            temperature: 0.3,
                                                                                                                                                                                                                                                                                                                                                  max_tokens:  1024,
                                                                                                                                                                                                                                                                                                                                                        top_p:       1.0,
                                                                                                                                                                                                                                                                                                                                                              messages:    body.messages || buildMessages(question, studentAnswer, marks || 3, topic || ''),
                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                      // Forward to Groq
                                                                                                                                                                                                                                                                                                                                                                          let groqRes;
                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                    groqRes = await fetch(GROQ_ENDPOINT, {
                                                                                                                                                                                                                                                                                                                                                                                            method:  'POST',
                                                                                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                                                                                              'Authorization': `Bearer ${env.GROQ_API_KEY}`,
                                                                                                                                                                                                                                                                                                                                                                                                                        'Content-Type':  'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify(groqBody),
                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return jsonResponse({ error: `Upstream fetch failed: ${err.message}` }, 502, origin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Surface Groq errors cleanly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!groqRes.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const errData = await groqRes.json().catch(() => ({}));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const msg = errData?.error?.message || `Groq API error ${groqRes.status}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return jsonResponse({ error: msg }, groqRes.status === 429 ? 429 : 502, origin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Stream Groq response straight back to browser
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const groqData = await groqRes.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return jsonResponse(groqData, 200, origin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ── Minimal message builder (fallback when client doesn't send messages[]) ──
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // The full few-shot examples live in the client; this is a lightweight fallback.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function buildMessages(question, studentAnswer, marks, topic) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const systemPrompt = `You are a T-Level Digital lead examiner. Analyse the student answer against the N.E.I. framework (Name, Explain, Impact). Output format:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          MARKS: X/${marks}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          N: [STATUS] — [one evidence sentence]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          E: [STATUS] — [one evidence sentence]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          I: [STATUS] — [one evidence sentence]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          VERDICT: [2-3 sentences, examiner register]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TO EARN THE NEXT MARK: [one concrete instruction]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Valid statuses: PRESENT, PARTIAL, MISSING, MISCONCEPTION. Plain text only. 80-150 words.`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { role: 'system', content: systemPrompt },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          role: 'user',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content: `QUESTION: ${question}\nMARKS AVAILABLE: ${marks}\nTOPIC: ${topic}\nSTUDENT ANSWER: "${studentAnswer}"`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
